### ISSUE TITLE
Screen recording alert - Android

### ISSUE THREAD

**Issue by guykogus** [Instabug/Instabug-Flutter#162]
Whenever triggering Instabug, whether by calling `Instabug.show()` or any of the invocation events, the first thing that pops up is some disclaimer about recording the screen. It doesn't matter if you dismiss the popup or press `Start recording`, afterwards you get the correct popup that offers to either report a bug or send a suggestion.
Is there any way to avoid this initial popup appearing?

**Comment by AliAbdelfattah** [comment]
@guykogus sorry I wasn't able to get back to you sooner. The disclaimer is being shown by the Android system when Media projection permission is being acquired, not sure we can work around that.

**Comment by guykogus** [comment]
@AliAbdelfattah in order to take a screenshot at the time of triggering Instabug, right? But then why does it present the disclaimer every time? Can't you just show it the once, by storing in shared preferences or something that it's already been displayed? That's what we do for a similar disclaimer for requesting access to background locations.

**Comment by jonchui** [comment]
I agree, this is very annoying on android to be shown every time.

**Comment by AliAbdelfattah** [comment]
We're working on a fix. Will keep the issue open till it gets released.

Meanwhile, we have created a snapshot if you want to give it a try.
```
      instabug_flutter:
        git:
          url: https://github.com/Instabug/instabug-flutter.git
          ref: snapshot-android/9.1.8.10-INSD-4986
```
