### ISSUE TITLE
Build warning: "The plugin `instabug_flutter` uses a deprecated version of the Android embedding"

### ISSUE THREAD

**Issue by pedromassango** [Instabug/Instabug-Flutter#200]
Here is the message I've got while building the Flutter app:

> The plugin `instabug_flutter` uses a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> 
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by AliAbdelfattah** [comment]
@pedromassango thank you for reporting this, we're looking into it.

**Comment by majdi21** [comment]
@AliAbdelfattah Are there any updates?

**Comment by dokind** [comment]
same here

**Comment by rabihmb** [comment]
The same

**Comment by HayfaAbusnina** [comment]
This error has happened because of flutter a new version. Until the packages update by the author to v2 Android embedding for the new flutter update.

**Comment by AliAbdelfattah** [comment]
We're releasing a fix this week. Meanwhile, here's a snapshot with the fix for anyone encountering the issue.

```
      instabug_flutter:
        git:
          url: https://github.com/Instabug/instabug-flutter.git
          ref: snapshot/10.8.0-android-plugin-v2
```
