### ISSUE TITLE
Thowing error 'E/IBG-APM (29392): Please refrain from using APMNetworkLogger.log as it is a private API'

### ISSUE THREAD

**Issue by RamithRD** [Instabug/Instabug-Flutter#309]
### Steps to Reproduce the Problem

Call an api via Dio, the SDK reports error in the debug console and none of the network logs are reflected on the Instabug console. All other APM features are working as intended. 

P.S. I'm using the sdk with debug mode enabled which allows the data to be synced with the dashboard once a session ends, skipping the 6hr batch sync.

### Expected Behavior

Ideally the network requests should be recorded in the console

### Actual Behavior

Throws the following log: 

E/IBG-APM (29392): Please refrain from using APMNetworkLogger.log as it is a private API

### Instabug integration code

Tested out in our main projects and also created a sample project to test, same behaviour on both projects.

```
final dio = Dio();
dio.interceptors.add(InstabugDioInterceptor());
var response = await dio.get('http://www.google.com');
```

### SDK Version
instabug_dio_interceptor: ^2.1.1
instabug_flutter: ^11.5.0

### Flutter, iOS and Android Versions
Flutter v3.3.5 - Stable Channel

**Comment by RamithRD** [comment]
I can recreate the same using `InstabugHttpClient` as well, so I assume this is related to APM module itself.

```
final client = InstabugHttpClient();
var response = await client.get(Uri.parse('http://www.google.com'));
```

**Comment by DavidMina96** [comment]
Hi @RamithRD, 

Thank you for reporting this issue. Indeed, a fix will be included in our next Flutter release. 

Until then, for anyone facing this issue, please use the below custom snapshot based on the current latest SDK version by adding it to your `pubspec.yaml` as follows:
```
dependencies:
  flutter:
    sdk: flutter
  # other dependencies...
  instabug_flutter:
    git:
      url: https://github.com/Instabug/instabug-flutter.git
      ref: snapshot/11.5.0-INSD-8704

dependency_overrides:
  instabug_flutter:
    git:
      url: https://github.com/Instabug/instabug-flutter.git
      ref: snapshot/11.5.0-INSD-8704
```
