### ISSUE TITLE
App Not building after on v12

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [Instabug/Instabug-Flutter#404]
The plugin worked fine earlier, but after updating it to v12 I am not able to run the app.

Throws this error:
<img width="1010" alt="image" src="https://github.com/Instabug/Instabug-Flutter/assets/113885801/5424c261-5b1d-4967-a96d-55f4c9cc1ef8">

```
* What went wrong:
Execution failed for task ':app:checkCaremonitorDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class a.a found in modules jetified-iHealthSDK_2.10.0 (iHealthSDK_2.10.0.jar) and jetified-instabug-apm-okhttp-interceptor-12.1.0-runtime (com.instabug.library:instabug-apm-okhttp-interceptor:12.1.0)

```

### Steps to Reproduce the Problem
Unfortunately, the other library iHealth SDK is private, So I cannot share the steps to replicate.

### SDK Version
instabug_flutter: ^12.1.0

### Flutter Version
Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-IN

**Comment by abdelhamid-f-nasser** [comment]
Hi @Gaurav-CareMonitor ,

Thank you for reporting this issue. We'll check it and keep you posted.

**Comment by Gaurav-CareMonitor** [comment]
Any updates @abdelhamid-f-nasser ?

**Comment by abdelhamid-f-nasser** [comment]
Hi @Gaurav-CareMonitor 👋,

This issue will be fixed in an upcoming release. In the meantime you can use the below 12.2.0 flutter snapshot to resolve this issue.

```yaml
dependencies:
  flutter:
    sdk: flutter
  # other dependencies...
  instabug_flutter:
    git:
      url: https://github.com/Instabug/instabug-flutter.git
      ref: snapshot/12.2.0-GH-404

# add this only if you have one of our network logging packages as a dependency
# to avoid resolution conflict between the package depending on instabug_flutter from pub.dev
# and the used instabug_flutter snapshot in dependencies.
dependency_overrides:
  instabug_flutter:
    git:
      url: https://github.com/Instabug/instabug-flutter.git
      ref: snapshot/12.2.0-GH-404
```
