### ISSUE TITLE
Namespace Dependency Required to Support Newer Gradle Versions

### ISSUE THREAD

**Issue by piyushlimited** [Instabug/Instabug-Flutter#499]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':instabug_flutter'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/piyush/.pub-cache/hosted/pub.dev/instabug_flutter-13.3.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by Turskyi** [comment]
Hi,

I am also experiencing this issue with the Instabug-Flutter library. Here are the details of my environment:

- Flutter version: 3.24.0
- Gradle version: 8.7
- Instabug-Flutter version: 13.3.0

Steps to reproduce:
1. Open Flutter project.
2. Go to android/gradle/wrapper/gradle-wrapper.properties
3. Set gradle version to gradle-8.7-bin.zip.
4. Sync the android project.
5. Try to run the flutter project on the physical android device (for example Pixel 6).
6. Observe the error.

Error message:
```
Launching lib/main.dart on Pixel 6 in debug mode… Running Gradle task ‘assembleDebug’…

FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring project ‘:instabug_flutter’.
Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl. Namespace not specified. Specify a namespace in the module’s build file: /Users/dmytro/.pub-cache/hosted/pub.dev/instabug_flutter-13.3.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

 If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. Get more help at https://help.gradle.org.

BUILD FAILED in 1s Error: Gradle task assembleDebug failed with exit code 1
```

Is there any additional information you need from my side to help resolve this issue?

Thank you!

**Comment by karimi1064** [comment]
Hello! I am also facing this issue.
```
Namespace not specified. Specify a namespace in the module's build file: /Users/maryam.karimi/.pub-cache/hosted/pub.dev/instabug_flutter-13.3.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```

**Comment by nicolasWenia** [comment]
Are there any news? Some of us are experiencing issues when targeting Android 14. Also Android 15 is out now, you should be updating these versions sooner.

**Comment by Turskyi** [comment]
Unbelievable

**Comment by a7medev** [comment]
Hello @piyushlimited, thanks for reporting this issue. Sorry for the late reply and the bot closing the issue.

We will look into it and get back to you. 🙏🏼

**Comment by dzwicker** [comment]
just add `namespace "com.instabug.flutter"` to the build.gradle file. It breaking all users build.

**Comment by bsz0206** [comment]
Hey instabug, this is ridiculous. is the company going bankrupt? This has been report more than 1 months ago and you have not cared at all. Also people tried to do it for you but their PRs are still waiting for your approval.

@a7medev

**Comment by a7medev** [comment]
Hello @dzwicker and @bsz0206, sorry for the miscommunication and the inconvenience, we made a fix for this issue already in #512 and it will be included in the upcoming release.

We've generated a snapshot with the fix so you can continue to use the SDK until the upcoming release. You can install it in your app by adding the following to your `pubspec.yaml` file:

```yaml
dependencies:
  instabug_flutter:
    git:
      url: https://github.com/Instabug/instabug-flutter.git
      ref: snapshot/13.4.0-INSD-12259

# Add this if you have one of our sub-packages (e.g. instabug_http_client) as a dependency
# to avoid resolution conflict between the package depending on instabug_flutter from pub.dev
# and the used instabug_flutter snapshot in dependencies.
dependency_overrides:
  instabug_flutter:
    git:
      url: https://github.com/Instabug/instabug-flutter.git
      ref: snapshot/13.4.0-INSD-12259
```
